### ISSUE TITLE
The signup process works fine?

### ISSUE THREAD

**Issue by uginy** [patelmayankce/angular-7-boilerplate#1]
Hi!

Good job man with your boilerplate!

But could you explain why i see the screen below? 
i've made just "yarn start" and can't test the  signup process

![image](https://user-images.githubusercontent.com/42149942/47958366-f1f08c80-dfd2-11e8-8a6f-c0092632629a.png)

**Comment by patelmayankce** [comment]
Hi,

Thanks to look into this!!

This boiler plat only include front end stuff.
I have another boiler plate for node framework HAPI 17. You can setup and change endpoint to make it working.

https://github.com/patelmayankce/hapi-17-boilerplate

**Comment by uginy** [comment]
Thanks. 
But what does it mean "You can setup and change endpoint" ? Could you explain please more detailed?
